apiVersion: apps/v1
kind: Deployment
metadata:
  name: snack-bar-api
  namespace: snack-bar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snack-bar-api
  template:
    metadata:
      labels:
        app: snack-bar-api
    spec:
      containers:
        - name: snack-bar-api
          image: deborasilveira/snack-bar-api:latest
          ports:
            - containerPort: 3000
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: snack-bar-secrets
                  key: POSTGRES_PASSWORD
            - name: DATABASE_URL
              value: "postgresql://root:$(POSTGRES_PASSWORD)@snack-bar-db:5432/snack-api-db"
          resources:
            requests:
              cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-webhook-api
  namespace: snack-bar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-webhook-api
  template:
    metadata:
      labels:
        app: payment-webhook-api
    spec:
      containers:
        - name: payment-webhook-api
          image: deborasilveira/payment-webhook-api:latest
          ports:
            - containerPort: 3001
          env:
            - name: MERCADO_PAGO_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: snack-bar-secrets
                  key: MERCADO_PAGO_ACCESS_TOKEN
            - name: MERCADO_PAGO_API_URL
              value: "https://api.mercadopago.com/v1"
          resources:
            requests:
              cpu: 100m
