apiVersion: v1
kind: Service
metadata:
  name: snack-bar-api
  namespace: snack-bar
spec:
  selector:
    app: snack-bar-api
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: payment-webhook-api
  namespace: snack-bar
spec:
  selector:
    app: payment-webhook-api
  ports:
    - port: 3001
      targetPort: 3001
  type: LoadBalancer
