apiVersion: v1
kind: PersistentVolume
metadata:
  name: snack-bar-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/data/snack-bar-db
