apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snack-bar-db-pvc
  namespace: snack-bar
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
