name: Terraform Workflow

on:
  pull_request:
    branches: ['main', 'development']
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform apply -auto-approve

      - name: Install kubectl
        if: github.event_name == 'push'
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Set up EKS kubeconfig
        if: github.event_name == 'push'
        run: |
          aws eks update-kubeconfig --name snack-bar-cluster --region ${{ secrets.AWS_REGION }}

      - name: Apply Kubernetes Manifests
        if: github.event_name == 'push'
        run: ./scripts/k8s-apply-script.sh
